#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

if (process.argv.length !== 5) {
  console.error('usage: build_provisioning_web.js <web-dir> <output.h> <symbol>');
  process.exit(2);
}

const webDir = process.argv[2];
const output = process.argv[3];
const symbol = process.argv[4];

const template = fs.readFileSync(path.join(webDir, 'index.html'), 'utf8');
const css = fs.readFileSync(path.join(webDir, 'styles.css'), 'utf8').trim();
const js = fs.readFileSync(path.join(webDir, 'app.js'), 'utf8').trim();

const html = template
  .replace('{{PROVISIONING_CSS}}', css)
  .replace('{{PROVISIONING_JS}}', js);

function cString(line) {
  return `"${line
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\r/g, '\\r')}"`;
}

const lines = html.split('\n');
const out = [];
out.push('/* Generated by scripts/build_provisioning_web.js. Do not edit directly. */');
out.push('#ifndef PROVISIONING_INDEX_HTML_H');
out.push('#define PROVISIONING_INDEX_HTML_H');
out.push('');
out.push(`static const char ${symbol}[] =`);
for (let i = 0; i < lines.length; i++) {
  out.push(`${cString(lines[i])}${i === lines.length - 1 ? ';' : ''}`);
}
out.push('');
out.push('#endif /* PROVISIONING_INDEX_HTML_H */');
out.push('');

fs.mkdirSync(path.dirname(output), { recursive: true });
fs.writeFileSync(output, out.join('\n'));
